{
  "class": "vulnerability",
  "id": "oval:com.ubuntu.focal:def:2017183420000000",
  "version": "1",
  "metadata": {
    "Title": "CVE-2017-18342 on Ubuntu 20.04 ESM (focal) - low.",
    "Description": "In PyYAML before 5.1, the yaml.load() API could execute arbitrary code if used with untrusted data. The load() function has been deprecated in version 5.1 and the 'UnsafeLoader' has been introduced for backward compatibility with the function.\n\nUpdate Instructions:\n\nRun `sudo pro fix CVE-2017-18342` to fix the vulnerability. The problem can be corrected\nby updating your system to the following package versions:\n\npython-yaml - 5.1.2-1\npython3-yaml - 5.1.2-1\nNo subscription required",
    "affected": {
      "family": "unix",
      "Platform": "Ubuntu 20.04 ESM"
    },
    "reference": {
      "source": "CVE",
      "ref_id": "CVE-2017-18342",
      "ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-18342"
    },
    "advisory": {
      "Severity": "Low",
      "Rights": "Copyright (C) 2018 Canonical Ltd.",
      "PublicDate": "2018-06-27 12:29:00 UTC",
      "Bug": [
        "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902878"
      ],
      "cve": {
        "text": "CVE-2017-18342",
        "href": "https://ubuntu.com/security/CVE-2017-18342",
        "public": "20180627",
        "cvss_score": "9.8",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
      },
      "PublicDateAtUsn": "",
      "AssignedTo": "",
      "DiscoveredBy": "",
      "Crd": "",
      "Ref": null
    }
  },
  "notes": {
    "Note": "seth-arnold> The patch changes the incredibly-unsafe yaml.load to the behaviour of safe_load; despite being many years overdue, it's also likely to break something. mdeslaur> upstream has reverted the 4.1 fix, so as of 2020-10-06, there is no proper fix for this issue for stable releases, and fixing it is likely to cause compatibility issues. In stable releases individual software would need to be fixed instead of pyyaml itself. We are not going to be fixing pyyaml itself, marking as ignored."
  },
  "criteria": {
    "criterions": [
      {
        "test_ref": "oval:com.ubuntu.focal:tst:2017183420000000",
        "comment": "pyyaml package in focal, is related to the CVE in some way and has been fixed (note: '5.1.2-1')."
      }
    ]
  }
}
