{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.trusty:def:201810008020000000",
	"version": "1",
	"metadata": {
		"Title": "CVE-2018-1000802 on Ubuntu 14.04 ESM (trusty) - medium",
		"Description": "Python Software Foundation Python (CPython) version 2.7 contains a CWE-77:Improper Neutralization of Special Elements used in a Command ('CommandInjection') vulnerability in shutil module (make_archive function) that canresult in Denial of service, Information gain via injection of arbitraryfiles on the system or entire drive. This attack appear to be exploitablevia Passage of unfiltered user input to the function. This vulnerabilityappears to have been fixed in after commitadd531a1e55b0a739b0f42582f1c9747e5649ace.\n\n    Update Instructions:\n\n    Run `sudo pro fix CVE-2018-1000802` to fix the vulnerability. The problem can be corrected\n    by updating your system to the following package versions:\n\nidle-python2.7 - 2.7.6-8ubuntu0.5\nlibpython2.7 - 2.7.6-8ubuntu0.5\nlibpython2.7-minimal - 2.7.6-8ubuntu0.5\nlibpython2.7-stdlib - 2.7.6-8ubuntu0.5\nlibpython2.7-testsuite - 2.7.6-8ubuntu0.5\npython2.7 - 2.7.6-8ubuntu0.5\npython2.7-examples - 2.7.6-8ubuntu0.5\npython2.7-minimal - 2.7.6-8ubuntu0.5\nNo subscription required\n\nidle-python3.4 - 3.4.3-1ubuntu1~14.04.7\nlibpython3.4 - 3.4.3-1ubuntu1~14.04.7\nlibpython3.4-minimal - 3.4.3-1ubuntu1~14.04.7\nlibpython3.4-stdlib - 3.4.3-1ubuntu1~14.04.7\nlibpython3.4-testsuite - 3.4.3-1ubuntu1~14.04.7\npython3.4 - 3.4.3-1ubuntu1~14.04.7\npython3.4-examples - 3.4.3-1ubuntu1~14.04.7\npython3.4-minimal - 3.4.3-1ubuntu1~14.04.7\npython3.4-venv - 3.4.3-1ubuntu1~14.04.7\nNo subscription required",
		"affected": {
			"family": "unix",
			"Platform": "Ubuntu 14.04 ESM"
		},
		"reference": {
			"source": "CVE",
			"ref_id": "CVE-2018-1000802",
			"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-1000802"
		},
		"advisory": {
			"Severity": "Medium",
			"Rights": "Copyright (C) 2018 Canonical Ltd.",
			"PublicDate": "2018-09-18",
			"Bug": [
				"https://bugs.python.org/issue34540"
			],
			"cve": {
				"text": "CVE-2018-1000802",
				"href": "https://ubuntu.com/security/CVE-2018-1000802",
				"public": "20180918",
				"cvss_score": "9.8",
				"cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
				"usns": "3817-1,3817-2"
			},
			"PublicDateAtUsn": "2018-09-18",
			"AssignedTo": "mdeslaur",
			"DiscoveredBy": "",
			"Crd": "",
			"Ref": [
				"https://ubuntu.com/security/notices/USN-3817-1",
				"https://ubuntu.com/security/notices/USN-3817-2"
			]
		}
	},
	"notes": {
		"Note": ""
	},
	"criteria": {
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:com.ubuntu.trusty:tst:201810000300000000",
						"comment": "python2.7 package in trusty was vulnerable but has been fixed (note: '2.7.6-8ubuntu0.5')."
					},
					{
						"test_ref": "oval:com.ubuntu.trusty:tst:201810008020000000",
						"comment": "python3.4 package in trusty was vulnerable but has been fixed (note: '3.4.3-1ubuntu1~14.04.7')."
					}
				]
			}
		]
	}
}
