{
	"class": "patch",
	"id": "oval:com.ubuntu.lunar:def:63781000000",
	"version": "1",
	"metadata": {
		"title": "USN-6378-1 -- Django vulnerability",
		"description": "It was discovered that Django incorrectly handled certain URIs with a very large number of Unicode characters. A remote attacker could possibly use this issue to cause Django to consume resources or crash, leading to a denial of service.  Update Instructions:  Run `sudo pro fix USN-6378-1` to fix the vulnerability. The problem can be corrected by updating your system to the following package versions:  python3-django - 3:3.2.18-1ubuntu0.4 python-django-doc - 3:3.2.18-1ubuntu0.4 No subscription required",
		"affected": {
			"family": "unix",
			"platform": "Ubuntu 23.04"
		},
		"reference": [
			{
				"source": "USN",
				"ref_id": "USN-6378-1",
				"ref_url": "https://ubuntu.com/security/notices/USN-6378-1"
			},
			{
				"source": "CVE",
				"ref_id": "CVE-2023-41164",
				"ref_url": "https://ubuntu.com/security/CVE-2023-41164"
			}
		],
		"advisory": {
			"from": "security@ubuntu.com",
			"severity": "Medium",
			"issued": {
				"date": "2023-09-18"
			},
			"cve": [
				{
					"text": "CVE-2023-41164",
					"href": "https://ubuntu.com/security/CVE-2023-41164",
					"priority": "medium",
					"public": "20230904",
					"cvss_score": "7.5",
					"cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
					"cvss_severity": "high",
					"usns": "6378-1,6414-2"
				}
			]
		}
	},
	"criteria": {
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:com.ubuntu.lunar:tst:637810000000",
						"comment": "Interim Release"
					}
				]
			}
		]
	}
}
