{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.bionic:def:2021454520000000",
	"version": "1",
	"metadata": {
		"Title": "CVE-2021-45452 on Ubuntu 18.04 ESM (bionic) - low",
		"Description": "Storage.save in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before4.0.1 allows directory traversal if crafted filenames are directly passedto it.\n\n    Update Instructions:\n\n    Run `sudo pro fix CVE-2021-45452` to fix the vulnerability. The problem can be corrected\n    by updating your system to the following package versions:\n\npython-django - 1:1.11.11-1ubuntu1.15\npython-django-common - 1:1.11.11-1ubuntu1.15\npython3-django - 1:1.11.11-1ubuntu1.15\nAvailable with Ubuntu Pro (Infra-only): https://ubuntu.com/pro",
		"affected": {
			"family": "unix",
			"Platform": "Ubuntu 18.04 ESM"
		},
		"reference": {
			"source": "CVE",
			"ref_id": "CVE-2021-45452",
			"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45452"
		},
		"advisory": {
			"Severity": "Low",
			"Rights": "Copyright (C) 2022 Canonical Ltd.",
			"PublicDate": "2022-01-04 10:00:00 UTC",
			"Bug": null,
			"cve": {
				"text": "CVE-2021-45452",
				"href": "https://ubuntu.com/security/CVE-2021-45452",
				"public": "20220104",
				"cvss_score": "5.3",
				"cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
				"usns": "5204-1"
			},
			"PublicDateAtUsn": "2022-01-04 10:00:00 UTC",
			"AssignedTo": "mdeslaur",
			"DiscoveredBy": "",
			"Crd": "",
			"Ref": [
				"https://ubuntu.com/security/notices/USN-5204-1"
			]
		}
	},
	"notes": {
		"Note": ""
	},
	"criteria": {
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:com.ubuntu.bionic:tst:2021451150000000",
						"comment": "python-django package in esm-infra/bionic was vulnerable but has been fixed (note: '1:1.11.11-1ubuntu1.15')."
					}
				]
			}
		]
	}
}
