{
  "class": "vulnerability",
  "id": "oval:com.ubuntu.bionic:def:202074710000000",
  "version": "1",
  "metadata": {
    "Title": "CVE-2020-7471 on Ubuntu 18.04 ESM (bionic) - medium.",
    "Description": "Django 1.11 before 1.11.28, 2.2 before 2.2.10, and 3.0 before 3.0.3 allows SQL Injection if untrusted data is used as a StringAgg delimiter (e.g., in Django applications that offer downloads of data as a series of rows with a user-specified column delimiter). By passing a suitably crafted delimiter to a contrib.postgres.aggregates.StringAgg instance, it was possible to break escaping and inject malicious SQL.\n\nUpdate Instructions:\n\nRun `sudo pro fix CVE-2020-7471` to fix the vulnerability. The problem can be corrected\nby updating your system to the following package versions:\n\npython-django - 1:1.11.11-1ubuntu1.7\npython-django-common - 1:1.11.11-1ubuntu1.7\npython3-django - 1:1.11.11-1ubuntu1.7\nAvailable with Ubuntu Pro (Infra-only): https://ubuntu.com/pro",
    "affected": {
      "family": "unix",
      "Platform": "Ubuntu 18.04 ESM"
    },
    "reference": {
      "source": "CVE",
      "ref_id": "CVE-2020-7471",
      "ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-7471"
    },
    "advisory": {
      "Severity": "Medium",
      "Rights": "Copyright (C) 2020 Canonical Ltd.",
      "PublicDate": "2020-02-03 10:00:00 UTC",
      "Bug": null,
      "cve": {
        "text": "CVE-2020-7471",
        "href": "https://ubuntu.com/security/CVE-2020-7471",
        "public": "20200203",
        "cvss_score": "9.8",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "usns": "4264-1"
      },
      "PublicDateAtUsn": "2020-02-03 10:00:00 UTC",
      "AssignedTo": "alexmurray",
      "DiscoveredBy": "Simon Charette",
      "Crd": "2020-02-03 10:00:00 UTC",
      "Ref": null
    }
  },
  "notes": {
    "Note": ""
  },
  "criteria": {
    "criterions": [
      {
        "test_ref": "oval:com.ubuntu.bionic:tst:202074710000000",
        "comment": "python-django package in bionic was vulnerable but has been fixed (note: '1:1.11.11-1ubuntu1.7')."
      }
    ]
  }
}
