{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.impish:def:202135720000000",
	"version": "1",
	"metadata": {
		"title": "CVE-2021-3572 on Ubuntu 21.10 (impish) - low.",
		"description": "A flaw was found in python-pip in the way it handled Unicode separators in git references. A remote attacker could possibly use this issue to install a different revision on a repository. The highest threat from this vulnerability is to data integrity. This is fixed in python-pip version 21.1.\n\nUpdate Instructions:\n\nRun `sudo ua fix CVE-2021-3572` to fix the vulnerability. The problem can be corrected\nby updating your system to the following package versions:\n\npython-pip-whl - 20.3.4-4\npython3-pip - 20.3.4-4\nNo subscription required",
		"affected": {
			"family": "unix",
			"platform": "Ubuntu 21.10"
		},
		"reference": {
			"source": "CVE",
			"ref_id": "CVE-2021-3572",
			"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3572"
		},
		"advisory": {
			"severity": "Low",
			"rights": "Copyright (C) 2021 Canonical Ltd.",
			"public_date": "2021-11-10 18:15:00 UTC",
			"bug": [
				"https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1926957"
			],
			"cve": {},
			"assigned_to": "litios",
			"ref": [
				"https://ubuntu.com/security/CVE-2021-3572",
				"https://github.com/pypa/pip/pull/9827",
				"https://github.com/pypa/pip/issues/10042",
				"https://github.com/pypa/pip/issues/10042#issuecomment-857452480",
				"https://github.com/skazi0/CVE-2021-3572/blob/master/CVE-2021-3572-v9.0.1.patch"
			]
		}
	},
	"notes": {
		"note": "sbeattie> pip < 10, i.e. pip in bionic and older, parses git references differently, requiring a more significant backport"
	},
	"criteria": {
		"criterions": [
			{
				"test_ref": "oval:com.ubuntu.impish:tst:2021335030000000",
				"comment": "python-pip package in impish, is related to the CVE in some way and has been fixed (note: '20.3.4-4')."
			}
		]
	}
}
