{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.xenial:def:2021343420000000",
	"version": "1",
	"metadata": {
		"title": "CVE-2021-34342 on Ubuntu 16.04 LTS (xenial) - medium",
		"description": "(Ming 0.4.8 has an out-of-bounds read vulnerability in the function new...)",
		"affected": {
			"family": "unix",
			"platform": "Ubuntu 16.04 LTS"
		},
		"reference": {
			"source": "CVE",
			"ref_id": "CVE-2021-34342",
			"ref_url": "https://www.cve.org/CVERecord?id=CVE-2021-34342"
		},
		"advisory": {
			"severity": "Medium",
			"rights": "Copyright (C) 2024 Canonical Ltd.",
			"public_date": "2024-09-09",
			"bug": [
				"https://github.com/libming/libming/issues/205"
			],
			"cve": {
				"text": "CVE-2021-34342",
				"href": "https://ubuntu.com/security/CVE-2021-34342",
				"public": "20240909",
				"cvss_score": "6.5",
				"cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:N/A:N"
			}
		}
	},
	"notes": {},
	"criteria": {
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:com.ubuntu.xenial:tst:201692640000000",
						"comment": "ming package in xenial is affected and may need fixing."
					}
				]
			}
		]
	}
}
