{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.xenial:def:201639530000000",
	"version": "1",
	"metadata": {
		"Title": "CVE-2016-3953 on Ubuntu 16.04 LTS (xenial) - low",
		"Description": "The sample web application in web2py before 2.14.2 might allow remoteattackers to execute arbitrary code via vectors involving use of ahardcoded encryption key when calling the session.connect function.\n\n    Update Instructions:\n\n    Run `sudo pro fix CVE-2016-3953` to fix the vulnerability. The problem can be corrected\n    by updating your system to the following package versions:\n\npython-gluon - 2.12.3-1ubuntu0.1\npython-web2py - 2.12.3-1ubuntu0.1\nNo subscription required",
		"affected": {
			"family": "unix",
			"Platform": "Ubuntu 16.04 LTS"
		},
		"reference": {
			"source": "CVE",
			"ref_id": "CVE-2016-3953",
			"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-3953"
		},
		"advisory": {
			"Severity": "Low",
			"Rights": "Copyright (C) 2018 Canonical Ltd.",
			"PublicDate": "2018-02-06",
			"Bug": null,
			"cve": {
				"text": "CVE-2016-3953",
				"href": "https://ubuntu.com/security/CVE-2016-3953",
				"public": "20180206",
				"cvss_score": "9.8",
				"cvss_vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
				"usns": "4030-1"
			},
			"PublicDateAtUsn": "2018-02-06",
			"AssignedTo": "",
			"DiscoveredBy": "",
			"Crd": "",
			"Ref": [
				"https://ubuntu.com/security/notices/USN-4030-1"
			]
		}
	},
	"notes": {
		"Note": ""
	},
	"criteria": {
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:com.ubuntu.xenial:tst:2016103210000000",
						"comment": "web2py package in xenial was vulnerable but has been fixed (note: '2.12.3-1ubuntu0.1')."
					}
				]
			}
		]
	}
}
