{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.xenial:def:2024534320000000",
	"version": "1",
	"metadata": {
		"title": "CVE-2024-53432 on Ubuntu 16.04 LTS (xenial) - medium",
		"description": "While parsing certain malformed PLY files, PCL version 1.14.1 crashes dueto an uncaught std::out_of_range exception in PCLPointCloud2::at. Thisissue could potentially be exploited to cause a denial-of-service (DoS)attack when processing untrusted PLY files.",
		"affected": {
			"family": "unix",
			"platform": "Ubuntu 16.04 LTS"
		},
		"reference": {
			"source": "CVE",
			"ref_id": "CVE-2024-53432",
			"ref_url": "https://www.cve.org/CVERecord?id=CVE-2024-53432"
		},
		"advisory": {
			"severity": "Medium",
			"rights": "Copyright (C) 2024 Canonical Ltd.",
			"public_date": "2024-11-21 18:15:00 UTC",
			"bug": [
				"http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1088186"
			],
			"cve": {
				"text": "CVE-2024-53432",
				"href": "https://ubuntu.com/security/CVE-2024-53432",
				"public": "20241121"
			},
			"assigned_to": "nic89"
		}
	},
	"notes": {},
	"criteria": {
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:com.ubuntu.xenial:tst:2024534320000000",
						"comment": "pcl package in xenial is affected and may need fixing."
					}
				]
			}
		]
	}
}
