{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.focal:def:2023243290000000",
	"version": "1",
	"metadata": {
		"title": "CVE-2023-24329 on Ubuntu 20.04 LTS (focal) - medium",
		"description": "An issue in the urllib.parse component of Python before 3.11.4 allowsattackers to bypass blocklisting methods by supplying a URL that startswith blank characters.\n\n    Update Instructions:\n\n    Run `sudo pro fix CVE-2023-24329` to fix the vulnerability. The problem can be corrected\n    by updating your system to the following package versions:\n\nidle-python3.8 - 3.8.10-0ubuntu1~20.04.8\nlibpython3.8 - 3.8.10-0ubuntu1~20.04.8\nlibpython3.8-minimal - 3.8.10-0ubuntu1~20.04.8\nlibpython3.8-stdlib - 3.8.10-0ubuntu1~20.04.8\nlibpython3.8-testsuite - 3.8.10-0ubuntu1~20.04.8\npython3.8 - 3.8.10-0ubuntu1~20.04.8\npython3.8-examples - 3.8.10-0ubuntu1~20.04.8\npython3.8-full - 3.8.10-0ubuntu1~20.04.8\npython3.8-minimal - 3.8.10-0ubuntu1~20.04.8\npython3.8-venv - 3.8.10-0ubuntu1~20.04.8\nNo subscription required\n\nidle-python3.9 - 3.9.5-3ubuntu0~20.04.1+esm1\nlibpython3.9 - 3.9.5-3ubuntu0~20.04.1+esm1\nlibpython3.9-minimal - 3.9.5-3ubuntu0~20.04.1+esm1\nlibpython3.9-stdlib - 3.9.5-3ubuntu0~20.04.1+esm1\nlibpython3.9-testsuite - 3.9.5-3ubuntu0~20.04.1+esm1\npython3.9 - 3.9.5-3ubuntu0~20.04.1+esm1\npython3.9-examples - 3.9.5-3ubuntu0~20.04.1+esm1\npython3.9-full - 3.9.5-3ubuntu0~20.04.1+esm1\npython3.9-minimal - 3.9.5-3ubuntu0~20.04.1+esm1\npython3.9-venv - 3.9.5-3ubuntu0~20.04.1+esm1\nAvailable with Ubuntu Pro: https://ubuntu.com/pro",
		"affected": {
			"family": "unix",
			"platform": "Ubuntu 20.04 LTS"
		},
		"reference": {
			"source": "CVE",
			"ref_id": "CVE-2023-24329",
			"ref_url": "https://www.cve.org/CVERecord?id=CVE-2023-24329"
		},
		"advisory": {
			"severity": "Medium",
			"rights": "Copyright (C) 2023 Canonical Ltd.",
			"public_date": "2023-02-17 15:15:00 UTC",
			"bug": [
				"https://github.com/python/cpython/issues/102153"
			],
			"cve": {
				"text": "CVE-2023-24329",
				"href": "https://ubuntu.com/security/CVE-2023-24329",
				"public": "20230217",
				"cvss_score": "7.5",
				"cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
				"usns": "5888-1,5960-1,6139-1"
			},
			"public_date_at_usn": "2023-02-17 15:15:00 UTC",
			"ref": [
				"https://ubuntu.com/security/notices/USN-5888-1",
				"https://ubuntu.com/security/notices/USN-5960-1",
				"https://ubuntu.com/security/notices/USN-6139-1"
			]
		}
	},
	"notes": {},
	"criteria": {
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:com.ubuntu.focal:tst:2017182070000000",
						"comment": "python2.7 package in focal is affected and needs fixing."
					},
					{
						"test_ref": "oval:com.ubuntu.focal:tst:2022485640000000",
						"comment": "python3.8 package in focal was vulnerable but has been fixed (note: '3.8.10-0ubuntu1~20.04.8')."
					},
					{
						"test_ref": "oval:com.ubuntu.focal:tst:2015201070000020",
						"comment": "python3.9 package in focal was vulnerable but has been fixed (note: '3.9.5-3ubuntu0~20.04.1+esm1')."
					}
				]
			}
		]
	}
}
