{
  "class": "vulnerability",
  "id": "oval:com.ubuntu.jammy:def:2021332030000000",
  "version": "1",
  "metadata": {
    "Title": "CVE-2021-33203 on Ubuntu 22.04 ESM (jammy) - low.",
    "Description": "Django before 2.2.24, 3.x before 3.1.12, and 3.2.x before 3.2.4 has a potential directory traversal via django.contrib.admindocs. Staff members could use the TemplateDetailView view to check the existence of arbitrary files. Additionally, if (and only if) the default admindocs templates have been customized by application developers to also show file contents, then not only the existence but also the file contents would have been exposed. In other words, there is directory traversal outside of the template root directories.\n\nUpdate Instructions:\n\nRun `sudo pro fix CVE-2021-33203` to fix the vulnerability. The problem can be corrected\nby updating your system to the following package versions:\n\npython3-django - 2:2.2.24-1\nNo subscription required",
    "affected": {
      "family": "unix",
      "Platform": "Ubuntu 22.04 ESM"
    },
    "reference": {
      "source": "CVE",
      "ref_id": "CVE-2021-33203",
      "ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-33203"
    },
    "advisory": {
      "Severity": "Low",
      "Rights": "Copyright (C) 2021 Canonical Ltd.",
      "PublicDate": "2021-06-02 09:00:00 UTC",
      "Bug": null,
      "cve": {
        "text": "CVE-2021-33203",
        "href": "https://ubuntu.com/security/CVE-2021-33203",
        "public": "20210602",
        "cvss_score": "4.9",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:N/A:N",
        "usns": "4975-1,4975-2"
      },
      "PublicDateAtUsn": "2021-06-02 09:00:00 UTC",
      "AssignedTo": "mdeslaur",
      "DiscoveredBy": "Rasmus Lerchedahl Petersen and Rasmus Wriedt Larsen",
      "Crd": "2021-06-02 09:00:00 UTC",
      "Ref": null
    }
  },
  "notes": {
    "Note": ""
  },
  "criteria": {
    "criterions": [
      {
        "test_ref": "oval:com.ubuntu.jammy:tst:2021332030000000",
        "comment": "python-django package in jammy was vulnerable but has been fixed (note: '2:2.2.24-1')."
      }
    ]
  }
}
