{
  "class": "vulnerability",
  "id": "oval:com.ubuntu.jammy:def:2020261370000000",
  "version": "1",
  "metadata": {
    "Title": "CVE-2020-26137 on Ubuntu 22.04 LTS (jammy) - medium.",
    "Description": "urllib3 before 1.25.9 allows CRLF injection if the attacker controls the HTTP request method, as demonstrated by inserting CR and LF control characters in the first argument of putrequest(). NOTE: this is similar to CVE-2020-26116.\n\nUpdate Instructions:\n\nRun `sudo pro fix CVE-2020-26137` to fix the vulnerability. The problem can be corrected\nby updating your system to the following package versions:\n\npython3-pip - 20.1.1-2\npython3-pip-whl - 20.1.1-2\nNo subscription required\n\npython3-urllib3 - 1.25.9-1\nNo subscription required",
    "affected": {
      "family": "unix",
      "Platform": "Ubuntu 22.04 LTS"
    },
    "reference": {
      "source": "CVE",
      "ref_id": "CVE-2020-26137",
      "ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-26137"
    },
    "advisory": {
      "Severity": "Medium",
      "Rights": "Copyright (C) 2020 Canonical Ltd.",
      "PublicDate": "2020-09-30 00:00:00 UTC",
      "Bug": [
        "https://bugs.python.org/issue39603"
      ],
      "cve": {
        "text": "CVE-2020-26137",
        "href": "https://ubuntu.com/security/CVE-2020-26137",
        "public": "20200930",
        "cvss_score": "6.5",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
        "usns": "4570-1"
      },
      "PublicDateAtUsn": "2020-09-30 00:00:00 UTC",
      "AssignedTo": "mdeslaur",
      "DiscoveredBy": "",
      "Crd": "",
      "Ref": null
    }
  },
  "notes": {
    "Note": "mdeslaur> the python-pip package bundles python-urllib3 binaries when built. After updating python-urllib3, a no-change rebuild of python-pip is required."
  },
  "criteria": {
    "criterias": [
      {
        "operator": "OR",
        "criterions": [
          {
            "test_ref": "oval:com.ubuntu.jammy:tst:2020261370000000",
            "comment": "python-pip package in jammy, is related to the CVE in some way and has been fixed (note: '20.1.1-2')."
          },
          {
            "test_ref": "oval:com.ubuntu.jammy:tst:2020261370000010",
            "comment": "python-urllib3 package in jammy, is related to the CVE in some way and has been fixed (note: '1.25.9-1')."
          }
        ]
      }
    ]
  }
}
