{
	"class": "patch",
	"id": "oval:com.ubuntu.bionic:def:49021000000",
	"version": "1",
	"metadata": {
		"title": "USN-4902-1 -- Django vulnerability",
		"description": "Dennis Brinkrolf discovered that Django incorrectly handled certain filenames. A remote attacker could possibly use this issue to create or overwrite files in unexpected directories.  Update Instructions:  Run `sudo pro fix USN-4902-1` to fix the vulnerability. The problem can be corrected by updating your system to the following package versions:  python3-django - 1:1.11.11-1ubuntu1.12 python-django-doc - 1:1.11.11-1ubuntu1.12 python-django-common - 1:1.11.11-1ubuntu1.12 python-django - 1:1.11.11-1ubuntu1.12 No subscription required",
		"affected": {
			"family": "unix",
			"platform": "Ubuntu 18.04 LTS"
		},
		"reference": [
			{
				"source": "USN",
				"ref_id": "USN-4902-1",
				"ref_url": "https://ubuntu.com/security/notices/USN-4902-1"
			},
			{
				"source": "CVE",
				"ref_id": "CVE-2021-28658",
				"ref_url": "https://ubuntu.com/security/CVE-2021-28658"
			}
		],
		"advisory": {
			"from": "security@ubuntu.com",
			"severity": "Low",
			"issued": {
				"date": "2021-04-06"
			},
			"cve": [
				{
					"text": "CVE-2021-28658",
					"href": "https://ubuntu.com/security/CVE-2021-28658",
					"priority": "low",
					"public": "20210406",
					"cvss_score": "5.3",
					"cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
					"cvss_severity": "medium",
					"usns": "4902-1"
				}
			]
		}
	},
	"criteria": {
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:com.ubuntu.bionic:tst:490210000000",
						"comment": "Long Term Support"
					}
				]
			}
		]
	}
}
